// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmYbvtxX-L3_qtjobCKLHpbn1m94qR_xU',
    appId: '1:897214574604:web:328e5f2725469826c17e29',
    messagingSenderId: '897214574604',
    projectId: 'healthtrack-e34c1',
    authDomain: 'healthtrack-e34c1.firebaseapp.com',
    storageBucket: 'healthtrack-e34c1.firebasestorage.app',
    measurementId: 'G-KEHZ35BEV4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJuuPqxLeNcA4cICTmfb5zxkMFFh4QybY',
    appId: '1:897214574604:android:29e373458dbb7516c17e29',
    messagingSenderId: '897214574604',
    projectId: 'healthtrack-e34c1',
    storageBucket: 'healthtrack-e34c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzZOBJqhNA-Fqv0XhxsyF-hCDD4RWXxgw',
    appId: '1:897214574604:ios:80162cd71cf31464c17e29',
    messagingSenderId: '897214574604',
    projectId: 'healthtrack-e34c1',
    storageBucket: 'healthtrack-e34c1.firebasestorage.app',
    iosBundleId: 'com.pbl5.HealthTrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzZOBJqhNA-Fqv0XhxsyF-hCDD4RWXxgw',
    appId: '1:897214574604:ios:35d40e1af313e7e1c17e29',
    messagingSenderId: '897214574604',
    projectId: 'healthtrack-e34c1',
    storageBucket: 'healthtrack-e34c1.firebasestorage.app',
    iosBundleId: 'com.example.healthAppUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmYbvtxX-L3_qtjobCKLHpbn1m94qR_xU',
    appId: '1:897214574604:web:f90404b5ac454653c17e29',
    messagingSenderId: '897214574604',
    projectId: 'healthtrack-e34c1',
    authDomain: 'healthtrack-e34c1.firebaseapp.com',
    storageBucket: 'healthtrack-e34c1.firebasestorage.app',
    measurementId: 'G-4VJ9XQRNVG',
  );

}